{"pr_number": 1430, "pr_title": "Retain error information in SQLServerPreparedStatement.getMetaData exceptions", "pr_createdAt": "2020-09-17T01:12:39Z", "pr_url": "https://github.com/microsoft/mssql-jdbc/pull/1430", "timeline": [{"oid": "8cf1c55ae0331aca66e6812de419847cce18e092", "url": "https://github.com/microsoft/mssql-jdbc/commit/8cf1c55ae0331aca66e6812de419847cce18e092", "message": "Retain error information in SQLServerPreparedStatement.getMetaData exceptions\n\nFixes a bug in SQLServerPreparedStatement.buildExecuteMetaData which\ncaused the SqlState as returned from the server error to be discarded in\nthrown exceptions. The SqlState information is useful for application\nlevel error handling.\n\nNo tests are provided, as I can't get the test harness to run in my\nlocal environment. However, here are steps to reproduce the 'bad' exception\nwith no included SqlState:\n\n```java\nConnection conn = null;     // Fill in with SqlServer connection.\nconn.prepareStatement(\"s\");\nconn.getMetaData();         // Throws exception without SqlState.\n```", "committedDate": "2020-09-17T01:11:27Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ5NjExNzQ0OA==", "url": "https://github.com/microsoft/mssql-jdbc/pull/1430#discussion_r496117448", "bodyText": "Is adding SQLTimeoutException necessary here? Could you explain this a bit?", "author": "ulvii", "createdAt": "2020-09-28T17:28:48Z", "path": "src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java", "diffHunk": "@@ -1050,7 +1050,7 @@ else if (needsPrepare)\n     }\n \n     @Override\n-    public final java.sql.ResultSetMetaData getMetaData() throws SQLServerException {\n+    public final java.sql.ResultSetMetaData getMetaData() throws SQLServerException, SQLTimeoutException {", "originalCommit": "8cf1c55ae0331aca66e6812de419847cce18e092", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ5NjE1MzUwNQ==", "url": "https://github.com/microsoft/mssql-jdbc/pull/1430#discussion_r496153505", "bodyText": "Yes.  buildExecuteMetaData() previously caught and wrapped the SQLTimeoutException in another exception with less info.  That's been changed so that it's no longer caught, and it gets thrown directly.  The JDBC API allows for throwing this exception type, so it shouldn't be rethrown with less info.", "author": "danburkert", "createdAt": "2020-09-28T18:33:42Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ5NjExNzQ0OA=="}], "type": "inlineReview", "revised_code": null}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ5ODQ5NTc5Mg==", "url": "https://github.com/microsoft/mssql-jdbc/pull/1430#discussion_r498495792", "bodyText": "We're only catching a subset of exceptions possibly thrown from this class (SQLException -> SQLServerException) now, but we should also catch the other exceptions that could be thrown from here.", "author": "peterbae", "createdAt": "2020-10-01T20:28:20Z", "path": "src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java", "diffHunk": "@@ -1080,21 +1080,18 @@ else if (needsPrepare)\n      * @throws SQLServerException\n      * @return the result set containing the meta data\n      */\n-    private ResultSet buildExecuteMetaData() throws SQLServerException {\n+    private SQLServerResultSet buildExecuteMetaData() throws SQLServerException, SQLTimeoutException {\n         String fmtSQL = userSQL;\n \n-        ResultSet emptyResultSet = null;\n+        SQLServerResultSet emptyResultSet = null;\n         try {\n             fmtSQL = replaceMarkerWithNull(fmtSQL);\n             internalStmt = (SQLServerStatement) connection.createStatement();\n             emptyResultSet = internalStmt.executeQueryInternal(\"set fmtonly on \" + fmtSQL + \"\\nset fmtonly off\");\n-        } catch (SQLException sqle) {\n+        } catch (SQLServerException sqle) {", "originalCommit": "8cf1c55ae0331aca66e6812de419847cce18e092", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ5ODUwMTQxOA==", "url": "https://github.com/microsoft/mssql-jdbc/pull/1430#discussion_r498501418", "bodyText": "The point of this PR is to not catch exceptions.  All exceptions are now propagated, except the specific empty result set exception which is handled.  Previously all exceptions were caught, then a useless exception containing no details was thrown through SQLServerException.makeFromDriverError.  This PR does not change the circumstances under which exceptions are thrown, it simply ensures that the original exception is propagated with the useful details, instead of throwing a different exception with no information.  This is critical so that applications can handle errors appropriately.", "author": "danburkert", "createdAt": "2020-10-01T20:40:57Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ5ODQ5NTc5Mg=="}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ5ODk0NzgwNg==", "url": "https://github.com/microsoft/mssql-jdbc/pull/1430#discussion_r498947806", "bodyText": "I see, thanks for the explanation.", "author": "peterbae", "createdAt": "2020-10-02T17:14:39Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ5ODQ5NTc5Mg=="}], "type": "inlineReview", "revised_code": null}]}