{"data": {"repository": {"pullRequest": {"id": "MDExOlB1bGxSZXF1ZXN0NTA3MDAyNDAw", "number": 7341, "reviewThreads": {"totalCount": 1, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMC0yMFQxOTowMjowNlrOEv71Zg==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMC0yMFQxOTowMjowNlrOEv71Zg==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMzE4Njk4ODU0OnYy", "diffSide": "RIGHT", "path": "src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java", "isResolved": false, "comments": {"totalCount": 3, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMC0yMFQxOTowMjowNlrOHlM2_w==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMC0yMFQxOToxODoxNlrOHlNZWA==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUwODc3MDA0Nw==", "bodyText": "Maybe a stupid question - but is it wrong to just \"catch (Exception e)\" in a situation like this - where we don't care why it failed/what kind of an exception it was? Does catching any exception make it more reliable potentially... or are there reasons why it should be avoided?", "url": "https://github.com/IQSS/dataverse/pull/7341#discussion_r508770047", "createdAt": "2020-10-20T19:02:06Z", "author": {"login": "landreev"}, "path": "src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java", "diffHunk": "@@ -224,6 +227,20 @@ public boolean onSuccess(CommandContext ctxt, Object r) {\n             LoggingUtil.writeOnSuccessFailureLog(this, failureLogText,  dataset);\n             retVal = false;\n         }\n+        \n+        //re-indexing dataverses that have additional subjects\n+        if (!dataversesToIndex.isEmpty()){\n+            for (Dataverse dv : dataversesToIndex) {\n+                try {\n+                    Future<String> indexString = ctxt.index().indexDataverse(dv);\n+                } catch (IOException | SolrServerException e) {", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "8f8ff854754831296c6656f5332e56c3f034a215"}, "originalPosition": 27}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUwODc3MzUyMg==", "bodyText": "In general, but maybe not in this case, if we get an exception that is unexpected we want it to fail loudly so that we can address it in another way if necessary.", "url": "https://github.com/IQSS/dataverse/pull/7341#discussion_r508773522", "createdAt": "2020-10-20T19:08:18Z", "author": {"login": "sekmiller"}, "path": "src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java", "diffHunk": "@@ -224,6 +227,20 @@ public boolean onSuccess(CommandContext ctxt, Object r) {\n             LoggingUtil.writeOnSuccessFailureLog(this, failureLogText,  dataset);\n             retVal = false;\n         }\n+        \n+        //re-indexing dataverses that have additional subjects\n+        if (!dataversesToIndex.isEmpty()){\n+            for (Dataverse dv : dataversesToIndex) {\n+                try {\n+                    Future<String> indexString = ctxt.index().indexDataverse(dv);\n+                } catch (IOException | SolrServerException e) {", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUwODc3MDA0Nw=="}, "originalCommit": {"oid": "8f8ff854754831296c6656f5332e56c3f034a215"}, "originalPosition": 27}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUwODc3ODg0MA==", "bodyText": "OK, makes sense.", "url": "https://github.com/IQSS/dataverse/pull/7341#discussion_r508778840", "createdAt": "2020-10-20T19:18:16Z", "author": {"login": "landreev"}, "path": "src/main/java/edu/harvard/iq/dataverse/engine/command/impl/FinalizeDatasetPublicationCommand.java", "diffHunk": "@@ -224,6 +227,20 @@ public boolean onSuccess(CommandContext ctxt, Object r) {\n             LoggingUtil.writeOnSuccessFailureLog(this, failureLogText,  dataset);\n             retVal = false;\n         }\n+        \n+        //re-indexing dataverses that have additional subjects\n+        if (!dataversesToIndex.isEmpty()){\n+            for (Dataverse dv : dataversesToIndex) {\n+                try {\n+                    Future<String> indexString = ctxt.index().indexDataverse(dv);\n+                } catch (IOException | SolrServerException e) {", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUwODc3MDA0Nw=="}, "originalCommit": {"oid": "8f8ff854754831296c6656f5332e56c3f034a215"}, "originalPosition": 27}]}}]}}}, "rateLimit": {"limit": 5000, "remaining": 3172, "cost": 1, "resetAt": "2021-11-13T12:10:21Z"}}}