{"pr_number": 7843, "pr_title": "CB-6697 Don't ignore volume related error in AWS upscale", "pr_createdAt": "2020-04-20T17:07:07Z", "pr_url": "https://github.com/hortonworks/cloudbreak/pull/7843", "timeline": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxMTU1MzEwMQ==", "url": "https://github.com/hortonworks/cloudbreak/pull/7843#discussion_r411553101", "bodyText": "Is this change correct? Let's say I set the threshold to 5 instances and the fullNodeCount is 10 nodes and 3 fails. Then 5 < 7 and it will throw an error, but only 3 instances has failed.", "author": "keyki", "createdAt": "2020-04-20T17:18:55Z", "path": "cloud-template/src/main/java/com/sequenceiq/cloudbreak/cloud/template/compute/CloudFailureHandler.java", "diffHunk": "@@ -59,7 +59,7 @@ private void doRollback(AuthenticatedContext auth, List<CloudResourceStatus> fai\n         }\n         switch (stx.getAdjustmentType()) {\n             case EXACT:\n-                if (stx.getThreshold() > fullNodeCount - failures.size()) {\n+                if (stx.getThreshold() < fullNodeCount - failures.size()) {", "originalCommit": "c8ee0aec3d2ac36766c63bc4062286abd73ff5a1", "replyToReviewId": null, "replies": null, "type": "inlineReview"}, {"oid": "4328d2afd70a507e5a48c945bc0ce9a6fc396107", "url": "https://github.com/hortonworks/cloudbreak/commit/4328d2afd70a507e5a48c945bc0ce9a6fc396107", "message": "CB-6697 Don't ignore volume related error in AWS upscale", "committedDate": "2020-04-21T09:54:52Z", "type": "commit"}, {"oid": "4328d2afd70a507e5a48c945bc0ce9a6fc396107", "url": "https://github.com/hortonworks/cloudbreak/commit/4328d2afd70a507e5a48c945bc0ce9a6fc396107", "message": "CB-6697 Don't ignore volume related error in AWS upscale", "committedDate": "2020-04-21T09:54:52Z", "type": "forcePushed"}]}