{"pr_number": 4493, "pr_title": "Recover VM not able to attach the data disks which were attached before destroy", "pr_createdAt": "2020-11-23T08:15:22Z", "pr_url": "https://github.com/apache/cloudstack/pull/4493", "timeline": [{"oid": "426e347a238caa5dcef4fa8f101d426db7526243", "url": "https://github.com/apache/cloudstack/commit/426e347a238caa5dcef4fa8f101d426db7526243", "message": "Fix for the issue of recover VM not able to attach the data disks which are there before destroy in case of VMware", "committedDate": "2020-11-23T08:04:44Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUyOTIxMDk4Ng==", "url": "https://github.com/apache/cloudstack/pull/4493#discussion_r529210986", "bodyText": "@harikrishna-patnala Checked the changes done in the PR #4307, which is breaking the old behavior (On destroy VM, detach the data disks which are marked to be deleted, and keep other disks attached). and these changes are reverted here to bring back the old behavior. Am I correct?", "author": "sureshanaparti", "createdAt": "2020-11-24T05:25:20Z", "path": "server/src/main/java/com/cloud/vm/UserVmManagerImpl.java", "diffHunk": "@@ -2946,13 +2946,7 @@ public UserVm destroyVm(DestroyVMCmd cmd) throws ResourceUnavailableException, C\n \n         stopVirtualMachine(vmId, VmDestroyForcestop.value());\n ", "originalCommit": "426e347a238caa5dcef4fa8f101d426db7526243", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUyOTIyMzA5Mw==", "url": "https://github.com/apache/cloudstack/pull/4493#discussion_r529223093", "bodyText": "Yes @sureshanaparti", "author": "harikrishna-patnala", "createdAt": "2020-11-24T06:05:59Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUyOTIxMDk4Ng=="}], "type": "inlineReview", "revised_code": null}]}