{"data": {"repository": {"pullRequest": {"id": "MDExOlB1bGxSZXF1ZXN0Mzc5MDU2NDI4", "number": 2638, "reviewThreads": {"totalCount": 3, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wMi0yNFQxNjo0MTowOVrODiZX-Q==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wMi0yNFQxNjo0OToxM1rODiZkCw==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjM3MzkzOTEzOnYy", "diffSide": "RIGHT", "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "isResolved": true, "comments": {"totalCount": 3, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wMi0yNFQxNjo0MTowOVrOFtnn2A==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wMy0wNFQxNDoxMzoxNlrOFxuxxQ==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzM3OTQxNg==", "bodyText": "Though this occurs at shutdown, could it occur in other situations too?\nFor example another thread could use wakeup() against this thread - though I think we do?\nI'm wondering if we should pause and retry ... though at shutdown I'd be concerned we wait too long\nIf we really only think wakeup will be at shutdown then this handling is ok-ish, but it's one route out of the method where we don't log an audit message at all, which probably would be desirable?", "url": "https://github.com/odpi/egeria/pull/2638#discussion_r383379416", "createdAt": "2020-02-24T16:41:09Z", "author": {"login": "planetf1"}, "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "diffHunk": "@@ -97,58 +96,97 @@ private void publishEvent(String event) throws ConnectorCheckedException\n     {\n         final String methodName = \"publishEvent\";\n \n-        try\n-        {\n-            log.debug(\"Sending message {0}\" + event);\n-            ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n-            producer.send(record).get();\n-            messageSendCount++;\n-        }\n-        catch (ExecutionException | CancellationException | InterruptedException error)\n-        {\n-        /*\n-         * Issue #1876 moved the retry logic into the kafka producer\n-         */\n-            log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n-            KafkaOpenMetadataTopicConnectorAuditCode auditCode;\n-            auditCode = KafkaOpenMetadataTopicConnectorAuditCode.EVENT_SEND_IN_ERROR_LOOP;\n-            auditLog.logRecord(methodName,\n-                              auditCode.getLogMessageId(),\n-                              auditCode.getSeverity(),\n-                              auditCode.getFormattedLogMessage(topicName,\n-                                                                Long.toString(messageSendCount),\n-                                                                Long.toString(this.getSendBufferSize()),\n-                                                                error.getMessage()),\n-                                                                null,\n-                                                                auditCode.getSystemAction(),\n-                                                                auditCode.getUserAction());\n-        }\n-        catch (WakeupException error)\n-        {\n-            log.error(\"Wake up for shut down \" + error.toString());\n-        }\n-        catch (Throwable error)\n-        {\n-            log.error(\"Exception in sendEvent \" + error.toString());\n-            KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;\n-            String errorMessage = errorCode.getErrorMessageId() + errorCode.getFormattedErrorMessage(error.getClass().getName(),\n-                                                                                                     topicName,\n-                                                                                                     error.getMessage());\n-\n-            throw new ConnectorCheckedException(errorCode.getHTTPErrorCode(),\n-                                                this.getClass().getName(),\n-                                                methodName,\n-                                                errorMessage,\n-                                                errorCode.getSystemAction(),\n-                                                errorCode.getUserAction(),\n-                                                error);\n-        }\n-        finally\n+        boolean                  eventSent = false;\n+        long                     eventRetryCount = 0;\n+\n+        while (!eventSent)\n         {\n-            /*\n-             * Producers have a thread and an in memory buffer\n-             */\n-            producer.flush();\n+            try\n+            {\n+                log.debug(\"Sending message {0}\" + event);\n+                ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n+                producer.send(record).get();\n+                eventSent = true;\n+                messageSendCount++;\n+            }\n+            catch (ExecutionException error)\n+            {\n+                /*\n+                 * This may be a simple timeout or something else more\n+                 */\n+                log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n+\n+                if( !isExceptionRetryable(error)) {\n+                    /* kafka thinks this isn't a retryable problem */\n+                    /* so let the caller try */\n+                    log.error(\"Exception in sendEvent \" + error.toString());\n+                    KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;\n+                    String errorMessage = errorCode.getErrorMessageId() + errorCode.getFormattedErrorMessage(error.getClass().getName(),\n+                            topicName,\n+                            error.getMessage());\n+\n+                    throw new ConnectorCheckedException(errorCode.getHTTPErrorCode(),\n+                            this.getClass().getName(),\n+                            methodName,\n+                            errorMessage,\n+                            errorCode.getSystemAction(),\n+                            errorCode.getUserAction(),\n+                            error);\n+                }\n+                if (eventRetryCount == 10)\n+                {\n+                    /* we've retried now let the caller retry */\n+                    break;\n+                }\n+                else\n+                {\n+                    if (eventRetryCount == 0)\n+                    {\n+                        KafkaOpenMetadataTopicConnectorAuditCode auditCode;\n+\n+                        auditCode = KafkaOpenMetadataTopicConnectorAuditCode.EVENT_SEND_IN_ERROR_LOOP;\n+                        auditLog.logRecord(methodName,\n+                                           auditCode.getLogMessageId(),\n+                                           auditCode.getSeverity(),\n+                                           auditCode.getFormattedLogMessage(topicName,\n+                                                                            Long.toString(messageSendCount),\n+                                                                            Long.toString(this.getSendBufferSize()),\n+                                                                            error.getMessage()),\n+                                           null,\n+                                           auditCode.getSystemAction(),\n+                                           auditCode.getUserAction());\n+                    }\n+\n+                    eventRetryCount++;\n+                }\n+            }\n+            catch (WakeupException error)", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "2f59feefa4563f615206695d9aeb3b93da1af5a2"}, "originalPosition": 145}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzkwMjc1NQ==", "bodyText": "@planetf1 This code is actually original code that was removed as part of this first attempt to fix this issue. I put the behaviour back after getting feedback on the first fix. There is nothing the producer is doing that would cause kafka to throw this.", "url": "https://github.com/odpi/egeria/pull/2638#discussion_r383902755", "createdAt": "2020-02-25T14:13:20Z", "author": {"login": "wbittles"}, "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "diffHunk": "@@ -97,58 +96,97 @@ private void publishEvent(String event) throws ConnectorCheckedException\n     {\n         final String methodName = \"publishEvent\";\n \n-        try\n-        {\n-            log.debug(\"Sending message {0}\" + event);\n-            ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n-            producer.send(record).get();\n-            messageSendCount++;\n-        }\n-        catch (ExecutionException | CancellationException | InterruptedException error)\n-        {\n-        /*\n-         * Issue #1876 moved the retry logic into the kafka producer\n-         */\n-            log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n-            KafkaOpenMetadataTopicConnectorAuditCode auditCode;\n-            auditCode = KafkaOpenMetadataTopicConnectorAuditCode.EVENT_SEND_IN_ERROR_LOOP;\n-            auditLog.logRecord(methodName,\n-                              auditCode.getLogMessageId(),\n-                              auditCode.getSeverity(),\n-                              auditCode.getFormattedLogMessage(topicName,\n-                                                                Long.toString(messageSendCount),\n-                                                                Long.toString(this.getSendBufferSize()),\n-                                                                error.getMessage()),\n-                                                                null,\n-                                                                auditCode.getSystemAction(),\n-                                                                auditCode.getUserAction());\n-        }\n-        catch (WakeupException error)\n-        {\n-            log.error(\"Wake up for shut down \" + error.toString());\n-        }\n-        catch (Throwable error)\n-        {\n-            log.error(\"Exception in sendEvent \" + error.toString());\n-            KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;\n-            String errorMessage = errorCode.getErrorMessageId() + errorCode.getFormattedErrorMessage(error.getClass().getName(),\n-                                                                                                     topicName,\n-                                                                                                     error.getMessage());\n-\n-            throw new ConnectorCheckedException(errorCode.getHTTPErrorCode(),\n-                                                this.getClass().getName(),\n-                                                methodName,\n-                                                errorMessage,\n-                                                errorCode.getSystemAction(),\n-                                                errorCode.getUserAction(),\n-                                                error);\n-        }\n-        finally\n+        boolean                  eventSent = false;\n+        long                     eventRetryCount = 0;\n+\n+        while (!eventSent)\n         {\n-            /*\n-             * Producers have a thread and an in memory buffer\n-             */\n-            producer.flush();\n+            try\n+            {\n+                log.debug(\"Sending message {0}\" + event);\n+                ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n+                producer.send(record).get();\n+                eventSent = true;\n+                messageSendCount++;\n+            }\n+            catch (ExecutionException error)\n+            {\n+                /*\n+                 * This may be a simple timeout or something else more\n+                 */\n+                log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n+\n+                if( !isExceptionRetryable(error)) {\n+                    /* kafka thinks this isn't a retryable problem */\n+                    /* so let the caller try */\n+                    log.error(\"Exception in sendEvent \" + error.toString());\n+                    KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;\n+                    String errorMessage = errorCode.getErrorMessageId() + errorCode.getFormattedErrorMessage(error.getClass().getName(),\n+                            topicName,\n+                            error.getMessage());\n+\n+                    throw new ConnectorCheckedException(errorCode.getHTTPErrorCode(),\n+                            this.getClass().getName(),\n+                            methodName,\n+                            errorMessage,\n+                            errorCode.getSystemAction(),\n+                            errorCode.getUserAction(),\n+                            error);\n+                }\n+                if (eventRetryCount == 10)\n+                {\n+                    /* we've retried now let the caller retry */\n+                    break;\n+                }\n+                else\n+                {\n+                    if (eventRetryCount == 0)\n+                    {\n+                        KafkaOpenMetadataTopicConnectorAuditCode auditCode;\n+\n+                        auditCode = KafkaOpenMetadataTopicConnectorAuditCode.EVENT_SEND_IN_ERROR_LOOP;\n+                        auditLog.logRecord(methodName,\n+                                           auditCode.getLogMessageId(),\n+                                           auditCode.getSeverity(),\n+                                           auditCode.getFormattedLogMessage(topicName,\n+                                                                            Long.toString(messageSendCount),\n+                                                                            Long.toString(this.getSendBufferSize()),\n+                                                                            error.getMessage()),\n+                                           null,\n+                                           auditCode.getSystemAction(),\n+                                           auditCode.getUserAction());\n+                    }\n+\n+                    eventRetryCount++;\n+                }\n+            }\n+            catch (WakeupException error)", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzM3OTQxNg=="}, "originalCommit": {"oid": "2f59feefa4563f615206695d9aeb3b93da1af5a2"}, "originalPosition": 145}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4NzY5MDk0OQ==", "bodyText": "Good to stick with this for our immediate kafka fix - can consider revisiting with a new connector implementation", "url": "https://github.com/odpi/egeria/pull/2638#discussion_r387690949", "createdAt": "2020-03-04T14:13:16Z", "author": {"login": "planetf1"}, "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "diffHunk": "@@ -97,58 +96,97 @@ private void publishEvent(String event) throws ConnectorCheckedException\n     {\n         final String methodName = \"publishEvent\";\n \n-        try\n-        {\n-            log.debug(\"Sending message {0}\" + event);\n-            ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n-            producer.send(record).get();\n-            messageSendCount++;\n-        }\n-        catch (ExecutionException | CancellationException | InterruptedException error)\n-        {\n-        /*\n-         * Issue #1876 moved the retry logic into the kafka producer\n-         */\n-            log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n-            KafkaOpenMetadataTopicConnectorAuditCode auditCode;\n-            auditCode = KafkaOpenMetadataTopicConnectorAuditCode.EVENT_SEND_IN_ERROR_LOOP;\n-            auditLog.logRecord(methodName,\n-                              auditCode.getLogMessageId(),\n-                              auditCode.getSeverity(),\n-                              auditCode.getFormattedLogMessage(topicName,\n-                                                                Long.toString(messageSendCount),\n-                                                                Long.toString(this.getSendBufferSize()),\n-                                                                error.getMessage()),\n-                                                                null,\n-                                                                auditCode.getSystemAction(),\n-                                                                auditCode.getUserAction());\n-        }\n-        catch (WakeupException error)\n-        {\n-            log.error(\"Wake up for shut down \" + error.toString());\n-        }\n-        catch (Throwable error)\n-        {\n-            log.error(\"Exception in sendEvent \" + error.toString());\n-            KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;\n-            String errorMessage = errorCode.getErrorMessageId() + errorCode.getFormattedErrorMessage(error.getClass().getName(),\n-                                                                                                     topicName,\n-                                                                                                     error.getMessage());\n-\n-            throw new ConnectorCheckedException(errorCode.getHTTPErrorCode(),\n-                                                this.getClass().getName(),\n-                                                methodName,\n-                                                errorMessage,\n-                                                errorCode.getSystemAction(),\n-                                                errorCode.getUserAction(),\n-                                                error);\n-        }\n-        finally\n+        boolean                  eventSent = false;\n+        long                     eventRetryCount = 0;\n+\n+        while (!eventSent)\n         {\n-            /*\n-             * Producers have a thread and an in memory buffer\n-             */\n-            producer.flush();\n+            try\n+            {\n+                log.debug(\"Sending message {0}\" + event);\n+                ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n+                producer.send(record).get();\n+                eventSent = true;\n+                messageSendCount++;\n+            }\n+            catch (ExecutionException error)\n+            {\n+                /*\n+                 * This may be a simple timeout or something else more\n+                 */\n+                log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n+\n+                if( !isExceptionRetryable(error)) {\n+                    /* kafka thinks this isn't a retryable problem */\n+                    /* so let the caller try */\n+                    log.error(\"Exception in sendEvent \" + error.toString());\n+                    KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;\n+                    String errorMessage = errorCode.getErrorMessageId() + errorCode.getFormattedErrorMessage(error.getClass().getName(),\n+                            topicName,\n+                            error.getMessage());\n+\n+                    throw new ConnectorCheckedException(errorCode.getHTTPErrorCode(),\n+                            this.getClass().getName(),\n+                            methodName,\n+                            errorMessage,\n+                            errorCode.getSystemAction(),\n+                            errorCode.getUserAction(),\n+                            error);\n+                }\n+                if (eventRetryCount == 10)\n+                {\n+                    /* we've retried now let the caller retry */\n+                    break;\n+                }\n+                else\n+                {\n+                    if (eventRetryCount == 0)\n+                    {\n+                        KafkaOpenMetadataTopicConnectorAuditCode auditCode;\n+\n+                        auditCode = KafkaOpenMetadataTopicConnectorAuditCode.EVENT_SEND_IN_ERROR_LOOP;\n+                        auditLog.logRecord(methodName,\n+                                           auditCode.getLogMessageId(),\n+                                           auditCode.getSeverity(),\n+                                           auditCode.getFormattedLogMessage(topicName,\n+                                                                            Long.toString(messageSendCount),\n+                                                                            Long.toString(this.getSendBufferSize()),\n+                                                                            error.getMessage()),\n+                                           null,\n+                                           auditCode.getSystemAction(),\n+                                           auditCode.getUserAction());\n+                    }\n+\n+                    eventRetryCount++;\n+                }\n+            }\n+            catch (WakeupException error)", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzM3OTQxNg=="}, "originalCommit": {"oid": "2f59feefa4563f615206695d9aeb3b93da1af5a2"}, "originalPosition": 145}]}}, {"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjM3Mzk1Mzc1OnYy", "diffSide": "RIGHT", "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "isResolved": true, "comments": {"totalCount": 3, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wMi0yNFQxNjo0NToxM1rOFtnxSA==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wMy0wNFQxNDoxMzozOVrOFxuyxg==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzM4MTgzMg==", "bodyText": "I noticed in this method we are using time in 2 different units - around line 39. Seconds for recoverytime, milliseconds for regular sleep time. though handled correctly would be better to use consistent units?", "url": "https://github.com/odpi/egeria/pull/2638#discussion_r383381832", "createdAt": "2020-02-24T16:45:13Z", "author": {"login": "planetf1"}, "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "diffHunk": "@@ -206,11 +244,19 @@ public void run()\n             catch (Throwable   error)\n             {\n                 log.error(\"Bad exception from sending events \" + error.getMessage());\n-                this.recoverAfterError();\n+\n+                if( isExceptionRetryable(error) ) {\n+                    this.recoverAfterError();", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "2f59feefa4563f615206695d9aeb3b93da1af5a2"}, "originalPosition": 182}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzkwMzM0NA==", "bodyText": "@planetf1 again this code was there , but I'm happy to change it if Mandy agrees.", "url": "https://github.com/odpi/egeria/pull/2638#discussion_r383903344", "createdAt": "2020-02-25T14:14:18Z", "author": {"login": "wbittles"}, "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "diffHunk": "@@ -206,11 +244,19 @@ public void run()\n             catch (Throwable   error)\n             {\n                 log.error(\"Bad exception from sending events \" + error.getMessage());\n-                this.recoverAfterError();\n+\n+                if( isExceptionRetryable(error) ) {\n+                    this.recoverAfterError();", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzM4MTgzMg=="}, "originalCommit": {"oid": "2f59feefa4563f615206695d9aeb3b93da1af5a2"}, "originalPosition": 182}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4NzY5MTIwNg==", "bodyText": "Good to stick with this for our immediate kafka fix - can consider revisiting with a new connector implementation", "url": "https://github.com/odpi/egeria/pull/2638#discussion_r387691206", "createdAt": "2020-03-04T14:13:39Z", "author": {"login": "planetf1"}, "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "diffHunk": "@@ -206,11 +244,19 @@ public void run()\n             catch (Throwable   error)\n             {\n                 log.error(\"Bad exception from sending events \" + error.getMessage());\n-                this.recoverAfterError();\n+\n+                if( isExceptionRetryable(error) ) {\n+                    this.recoverAfterError();", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzM4MTgzMg=="}, "originalCommit": {"oid": "2f59feefa4563f615206695d9aeb3b93da1af5a2"}, "originalPosition": 182}]}}, {"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjM3Mzk3MDAzOnYy", "diffSide": "RIGHT", "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "isResolved": true, "comments": {"totalCount": 2, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wMi0yNFQxNjo0OToxM1rOFtn7Wg==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0wMy0wNFQxNDoxMzoyN1rOFxuyMg==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzM4NDQxMA==", "bodyText": "I notice the text for this event says the message isn't sent. True in terms of this connector's responsibility, but if queueing occurs further up the stack the message is confusing to the audit log reviewer", "url": "https://github.com/odpi/egeria/pull/2638#discussion_r383384410", "createdAt": "2020-02-24T16:49:13Z", "author": {"login": "planetf1"}, "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "diffHunk": "@@ -97,58 +96,97 @@ private void publishEvent(String event) throws ConnectorCheckedException\n     {\n         final String methodName = \"publishEvent\";\n \n-        try\n-        {\n-            log.debug(\"Sending message {0}\" + event);\n-            ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n-            producer.send(record).get();\n-            messageSendCount++;\n-        }\n-        catch (ExecutionException | CancellationException | InterruptedException error)\n-        {\n-        /*\n-         * Issue #1876 moved the retry logic into the kafka producer\n-         */\n-            log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n-            KafkaOpenMetadataTopicConnectorAuditCode auditCode;\n-            auditCode = KafkaOpenMetadataTopicConnectorAuditCode.EVENT_SEND_IN_ERROR_LOOP;\n-            auditLog.logRecord(methodName,\n-                              auditCode.getLogMessageId(),\n-                              auditCode.getSeverity(),\n-                              auditCode.getFormattedLogMessage(topicName,\n-                                                                Long.toString(messageSendCount),\n-                                                                Long.toString(this.getSendBufferSize()),\n-                                                                error.getMessage()),\n-                                                                null,\n-                                                                auditCode.getSystemAction(),\n-                                                                auditCode.getUserAction());\n-        }\n-        catch (WakeupException error)\n-        {\n-            log.error(\"Wake up for shut down \" + error.toString());\n-        }\n-        catch (Throwable error)\n-        {\n-            log.error(\"Exception in sendEvent \" + error.toString());\n-            KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;\n-            String errorMessage = errorCode.getErrorMessageId() + errorCode.getFormattedErrorMessage(error.getClass().getName(),\n-                                                                                                     topicName,\n-                                                                                                     error.getMessage());\n-\n-            throw new ConnectorCheckedException(errorCode.getHTTPErrorCode(),\n-                                                this.getClass().getName(),\n-                                                methodName,\n-                                                errorMessage,\n-                                                errorCode.getSystemAction(),\n-                                                errorCode.getUserAction(),\n-                                                error);\n-        }\n-        finally\n+        boolean                  eventSent = false;\n+        long                     eventRetryCount = 0;\n+\n+        while (!eventSent)\n         {\n-            /*\n-             * Producers have a thread and an in memory buffer\n-             */\n-            producer.flush();\n+            try\n+            {\n+                log.debug(\"Sending message {0}\" + event);\n+                ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n+                producer.send(record).get();\n+                eventSent = true;\n+                messageSendCount++;\n+            }\n+            catch (ExecutionException error)\n+            {\n+                /*\n+                 * This may be a simple timeout or something else more\n+                 */\n+                log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n+\n+                if( !isExceptionRetryable(error)) {\n+                    /* kafka thinks this isn't a retryable problem */\n+                    /* so let the caller try */\n+                    log.error(\"Exception in sendEvent \" + error.toString());\n+                    KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "2f59feefa4563f615206695d9aeb3b93da1af5a2"}, "originalPosition": 105}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4NzY5MTA1OA==", "bodyText": "Good to stick with this for our immediate kafka fix - can consider revisiting with a new connector implementation", "url": "https://github.com/odpi/egeria/pull/2638#discussion_r387691058", "createdAt": "2020-03-04T14:13:27Z", "author": {"login": "planetf1"}, "path": "open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventProducer.java", "diffHunk": "@@ -97,58 +96,97 @@ private void publishEvent(String event) throws ConnectorCheckedException\n     {\n         final String methodName = \"publishEvent\";\n \n-        try\n-        {\n-            log.debug(\"Sending message {0}\" + event);\n-            ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n-            producer.send(record).get();\n-            messageSendCount++;\n-        }\n-        catch (ExecutionException | CancellationException | InterruptedException error)\n-        {\n-        /*\n-         * Issue #1876 moved the retry logic into the kafka producer\n-         */\n-            log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n-            KafkaOpenMetadataTopicConnectorAuditCode auditCode;\n-            auditCode = KafkaOpenMetadataTopicConnectorAuditCode.EVENT_SEND_IN_ERROR_LOOP;\n-            auditLog.logRecord(methodName,\n-                              auditCode.getLogMessageId(),\n-                              auditCode.getSeverity(),\n-                              auditCode.getFormattedLogMessage(topicName,\n-                                                                Long.toString(messageSendCount),\n-                                                                Long.toString(this.getSendBufferSize()),\n-                                                                error.getMessage()),\n-                                                                null,\n-                                                                auditCode.getSystemAction(),\n-                                                                auditCode.getUserAction());\n-        }\n-        catch (WakeupException error)\n-        {\n-            log.error(\"Wake up for shut down \" + error.toString());\n-        }\n-        catch (Throwable error)\n-        {\n-            log.error(\"Exception in sendEvent \" + error.toString());\n-            KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;\n-            String errorMessage = errorCode.getErrorMessageId() + errorCode.getFormattedErrorMessage(error.getClass().getName(),\n-                                                                                                     topicName,\n-                                                                                                     error.getMessage());\n-\n-            throw new ConnectorCheckedException(errorCode.getHTTPErrorCode(),\n-                                                this.getClass().getName(),\n-                                                methodName,\n-                                                errorMessage,\n-                                                errorCode.getSystemAction(),\n-                                                errorCode.getUserAction(),\n-                                                error);\n-        }\n-        finally\n+        boolean                  eventSent = false;\n+        long                     eventRetryCount = 0;\n+\n+        while (!eventSent)\n         {\n-            /*\n-             * Producers have a thread and an in memory buffer\n-             */\n-            producer.flush();\n+            try\n+            {\n+                log.debug(\"Sending message {0}\" + event);\n+                ProducerRecord<String, String> record = new ProducerRecord<>(topicName, localServerId, event);\n+                producer.send(record).get();\n+                eventSent = true;\n+                messageSendCount++;\n+            }\n+            catch (ExecutionException error)\n+            {\n+                /*\n+                 * This may be a simple timeout or something else more\n+                 */\n+                log.debug(\"Kafka had trouble sending event: \" + event + \"exception message is \" + error.getMessage());\n+\n+                if( !isExceptionRetryable(error)) {\n+                    /* kafka thinks this isn't a retryable problem */\n+                    /* so let the caller try */\n+                    log.error(\"Exception in sendEvent \" + error.toString());\n+                    KafkaOpenMetadataTopicConnectorErrorCode errorCode = KafkaOpenMetadataTopicConnectorErrorCode.ERROR_SENDING_EVENT;", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM4MzM4NDQxMA=="}, "originalCommit": {"oid": "2f59feefa4563f615206695d9aeb3b93da1af5a2"}, "originalPosition": 105}]}}]}}}, "rateLimit": {"limit": 5000, "remaining": 2448, "cost": 1, "resetAt": "2021-11-12T20:28:25Z"}}}