{"data": {"repository": {"pullRequest": {"id": "MDExOlB1bGxSZXF1ZXN0NTMxMjc5MjUw", "number": 1993, "title": "Python Client: Error print statement now also prints exec_function name.", "bodyText": "Detecting errors happening when a workflow is running is somewhat difficult. When the workers log the problematic exec_function's name, it is much easier to detect the issue without having to view the Conductor UI.", "createdAt": "2020-12-02T20:44:23Z", "url": "https://github.com/Netflix/conductor/pull/1993", "merged": true, "mergeCommit": {"oid": "31828bfe72d541527e3d533d43d0465524481123"}, "closed": true, "closedAt": "2020-12-22T00:53:22Z", "author": {"login": "DPain"}, "timelineItems": {"totalCount": 3, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpPPAAABdiUtZkgH2gAyNTMxMjc5MjUwOjczZDFjZDhjMGVjNDIzMTE1NTI4MWI2NDlkOWJmZjk2NDgyOGYwYTA=", "endCursor": "Y3Vyc29yOnYyOpPPAAABdofvZbAFqTU1Njc1MjA0OQ==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"__typename": "PullRequestCommit", "commit": {"oid": "73d1cd8c0ec4231155281b649d9bff964828f0a0", "author": {"user": {"login": "DPain", "name": "D_Pain"}}, "url": "https://github.com/Netflix/conductor/commit/73d1cd8c0ec4231155281b649d9bff964828f0a0", "committedDate": "2020-12-02T20:38:21Z", "message": "Error print statement now also prints exec_function name."}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NTUyMDI1Njk3", "url": "https://github.com/Netflix/conductor/pull/1993#pullrequestreview-552025697", "createdAt": "2020-12-15T01:00:21Z", "commit": {"oid": "73d1cd8c0ec4231155281b649d9bff964828f0a0"}, "state": "COMMENTED", "comments": {"totalCount": 1, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMi0xNVQwMTowMDoyMVrOIFz6Ew==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMi0xNVQwMTowMDoyMVrOIFz6Ew==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDU0Mjk2NDI0Mw==", "bodyText": "What does exec_function.__name__ usually have? Can it be task name from the task object instead of a function name?", "url": "https://github.com/Netflix/conductor/pull/1993#discussion_r542964243", "createdAt": "2020-12-15T01:00:21Z", "author": {"login": "kishorebanala"}, "path": "client/python/conductor/ConductorWorker.py", "diffHunk": "@@ -78,7 +78,7 @@ def execute(self, task, exec_function):\n                 task['reasonForIncompletion'] = resp['reasonForIncompletion']\n             self.taskClient.updateTask(task)\n         except Exception as err:\n-            print('Error executing task: ' + str(err))\n+            print(f'Error executing task: {exec_function.__name__} with error: {str(err)}')", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "73d1cd8c0ec4231155281b649d9bff964828f0a0"}, "originalPosition": 5}]}}, {"__typename": "PullRequestReview", "id": "MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NTU2NzUyMDQ5", "url": "https://github.com/Netflix/conductor/pull/1993#pullrequestreview-556752049", "createdAt": "2020-12-22T00:53:02Z", "commit": {"oid": "73d1cd8c0ec4231155281b649d9bff964828f0a0"}, "state": "APPROVED", "comments": {"totalCount": 0, "pageInfo": {"startCursor": null, "endCursor": null, "hasNextPage": false, "hasPreviousPage": false}, "nodes": []}}]}}}, "rateLimit": {"limit": 5000, "remaining": 737, "cost": 1, "resetAt": "2021-11-01T15:33:45Z"}}}