{"data": {"repository": {"pullRequest": {"id": "MDExOlB1bGxSZXF1ZXN0NTI5MzY0ODIw", "number": 7647, "reviewThreads": {"totalCount": 1, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMi0wM1QxMDozNDoyNFrOFAJyKg==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMi0wM1QxMDozNDoyNFrOFAJyKg==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMzM1NzA0NjE4OnYy", "diffSide": "RIGHT", "path": "testsuite/model/pom.xml", "isResolved": true, "comments": {"totalCount": 4, "pageInfo": {"startCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMi0wM1QxMDozNDoyNFrOH-Sb0Q==", "endCursor": "Y3Vyc29yOnYyOpK0MjAyMC0xMi0wNFQxNTo1NDoyN1rOH_W_GA==", "hasNextPage": false, "hasPreviousPage": false}, "nodes": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUzNTA3NTc5Mw==", "bodyText": "When I run this combination locally I get\nCaused by: org.hibernate.HibernateException: The internal connection pool has reached its maximum size and no connection is currently available!\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.poll(DriverManagerConnectionProviderImpl.java:322)\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.getConnection(DriverManagerConnectionProviderImpl.java:189)\n\tat org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:254)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:262)\n\tat org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:236)\n\tat org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:86)\n\tat org.keycloak.connections.jpa.JpaKeycloakTransaction.begin(JpaKeycloakTransaction.java:42)\n\tat org.keycloak.services.DefaultKeycloakTransactionManager.enlist(DefaultKeycloakTransactionManager.java:54)\n\tat org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:92)\n\tat org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:59)\n\tat org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:274)\n\tat org.keycloak.models.jpa.JpaUserProviderFactory.create(JpaUserProviderFactory.java:51)\n\tat org.keycloak.models.jpa.JpaUserProviderFactory.create(JpaUserProviderFactory.java:33)\n\tat org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:274)\n\tat org.keycloak.services.DefaultKeycloakSession.userLocalStorage(DefaultKeycloakSession.java:194)\n\tat org.keycloak.storage.UserStorageManager.localStorage(UserStorageManager.java:78)\n\tat org.keycloak.storage.UserStorageManager.lambda$addUser$4(UserStorageManager.java:193)\n\nI need to investigate it further to know what is going on and if it's only env issue on my end.", "url": "https://github.com/keycloak/keycloak/pull/7647#discussion_r535075793", "createdAt": "2020-12-03T10:34:24Z", "author": {"login": "vramik"}, "path": "testsuite/model/pom.xml", "diffHunk": "@@ -127,14 +132,28 @@\n         <profile>\n             <id>jpa-federation+infinispan</id>", "state": "SUBMITTED", "replyTo": null, "originalCommit": {"oid": "ab15a9271a5e9f16870e88a96c782c5d7b5f7c26"}, "originalPosition": 14}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUzNTQwNjQ1NQ==", "bodyText": "Right, this happens sometimes in this settings. I cannot reproduce it reliably and is not caused by this PR. However I agree we should understand the cause. It has never occurred to me without the infinispan profile which is making it even more tricky", "url": "https://github.com/keycloak/keycloak/pull/7647#discussion_r535406455", "createdAt": "2020-12-03T16:52:28Z", "author": {"login": "hmlnarik"}, "path": "testsuite/model/pom.xml", "diffHunk": "@@ -127,14 +132,28 @@\n         <profile>\n             <id>jpa-federation+infinispan</id>", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUzNTA3NTc5Mw=="}, "originalCommit": {"oid": "ab15a9271a5e9f16870e88a96c782c5d7b5f7c26"}, "originalPosition": 14}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUzNjAzMDE3Ng==", "bodyText": "https://issues.redhat.com/browse/KEYCLOAK-16545", "url": "https://github.com/keycloak/keycloak/pull/7647#discussion_r536030176", "createdAt": "2020-12-04T11:25:15Z", "author": {"login": "vramik"}, "path": "testsuite/model/pom.xml", "diffHunk": "@@ -127,14 +132,28 @@\n         <profile>\n             <id>jpa-federation+infinispan</id>", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUzNTA3NTc5Mw=="}, "originalCommit": {"oid": "ab15a9271a5e9f16870e88a96c782c5d7b5f7c26"}, "originalPosition": 14}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUzNjE5ODkzNg==", "bodyText": "Thanks @vramik !", "url": "https://github.com/keycloak/keycloak/pull/7647#discussion_r536198936", "createdAt": "2020-12-04T15:54:27Z", "author": {"login": "hmlnarik"}, "path": "testsuite/model/pom.xml", "diffHunk": "@@ -127,14 +132,28 @@\n         <profile>\n             <id>jpa-federation+infinispan</id>", "state": "SUBMITTED", "replyTo": {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDUzNTA3NTc5Mw=="}, "originalCommit": {"oid": "ab15a9271a5e9f16870e88a96c782c5d7b5f7c26"}, "originalPosition": 14}]}}]}}}, "rateLimit": {"limit": 5000, "remaining": 3213, "cost": 1, "resetAt": "2021-11-12T20:28:25Z"}}}